-- INSERT PLANS --

INSERT INTO PLAN (ID, NAME, DESCRIPTION, MONTHLY_PRICE)
VALUES (1, 'Pet Avengers', 'The only option', '42,00');

-- INSERT CLIENTS --

INSERT INTO CLIENT (ID, ID_PLAN, NAME, EMAIL, PASSWORD, ADDRESS, CPF, DATE_OF_BIRTH)
VALUES (1, 1, 'Tony Stark', 't.stark@avenger.com', '40bd001563085fc35165329ea1ff5c5ecbdbbeef', 'Avengers Tower', '5', '29/03/1970');
INSERT INTO CLIENT (ID, ID_PLAN, NAME, EMAIL, PASSWORD, ADDRESS, CPF, DATE_OF_BIRTH)
VALUES (2, 1, 'Steve Rogers', 's.rogers@avenger.com', '40bd001563085fc35165329ea1ff5c5ecbdbbeef', 'Avengers Tower', '', '');
INSERT INTO CLIENT (ID, ID_PLAN, NAME, EMAIL, PASSWORD, ADDRESS, CPF, DATE_OF_BIRTH)
VALUES (3, 1, 'Thor', 't.odinson@avenger.com', '40bd001563085fc35165329ea1ff5c5ecbdbbeef', 'Avengers Tower', '', '');
INSERT INTO CLIENT (ID, ID_PLAN, NAME, EMAIL, PASSWORD, ADDRESS, CPF, DATE_OF_BIRTH)
VALUES (4, 1, 'Bruce Banner', 'b.banner@avenger.com', '40bd001563085fc35165329ea1ff5c5ecbdbbeef', 'Avengers Tower', '', '');
INSERT INTO CLIENT (ID, ID_PLAN, NAME, EMAIL, PASSWORD, ADDRESS, CPF, DATE_OF_BIRTH)
VALUES (5, 1, 'Natasha Romanoff', 'n.romanoff@avenger.com', '40bd001563085fc35165329ea1ff5c5ecbdbbeef', 'Avengers Tower', '', '');
INSERT INTO CLIENT (ID, ID_PLAN, NAME, EMAIL, PASSWORD, ADDRESS, CPF, DATE_OF_BIRTH)
VALUES (6, 1, 'Clint Barton', 'c.barton@avenger.com', '40bd001563085fc35165329ea1ff5c5ecbdbbeef', 'Avengers Tower', '', '');

-- INSERT PETS --

INSERT INTO PET (ID, ID_CLIENT, NAME, SPECIES, SIZE_TYPE, DATE_OF_BIRTH)
VALUES (1, 1, 'Name1', 'Species', 'Size Type', 'Date of Birth');
INSERT INTO PET (ID, ID_CLIENT, NAME, SPECIES, SIZE_TYPE, DATE_OF_BIRTH)
VALUES (2, 2, 'Name2', 'Species', 'Size Type', 'Date of Birth');
INSERT INTO PET (ID, ID_CLIENT, NAME, SPECIES, SIZE_TYPE, DATE_OF_BIRTH)
VALUES (3, 2, 'Name3', 'Species', 'Size Type', 'Date of Birth');

-- INSERT BUSINESSES --
INSERT INTO BUSINESS (ID, NAME, ADDRESS, CNPJ, BUSINESS_TYPE, SERVICES_AVAILABLE)
VALUES (1, 'NAME', 'ADDRESS', 'CNPJ', 'BUSINESS_TYPE', 'SERVICES_AVAILABLE');

-- INSERT BUSINESS_PLANS --
INSERT INTO BUSINESS_PLAN (ID, ID_PLAN, ID_BUSINESS)
VALUES (1, 1, 1);

-- INSERT APPOINTMENTS --
INSERT INTO APPOINTMENT (ID, ID_PET, ID_BUSINESS, APPOINTMENT_DATE, SERVICE_TYPE)
VALUES (1, 1, 1, 'APPOINTMENT_DATE', 'SERVICE_TYPE');

